
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { config } from "dotenv";
import { resolve } from "path";

// Load .env file from backend directory
config({ path: resolve(__dirname, ".env") });

// Get DATABASE_URL from environment - prefer DIRECT_URL for CLI operations (db push, migrations)
// DIRECT_URL should be the direct connection (without -pooler) from Neon dashboard
// For Neon: Use DIRECT_URL for CLI operations (db push, migrations), DATABASE_URL for app connections
const databaseUrl = process.env.DIRECT_URL || process.env.DATABASE_URL;

if (!databaseUrl) {
  console.error("❌ Neither DIRECT_URL nor DATABASE_URL found in environment variables");
  console.error("Please set DIRECT_URL or DATABASE_URL in your .env file");
  throw new Error("Database URL not found in environment variables");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
